#!/usr/bin/env bash
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	100
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	200
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	300
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	400
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	500
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	600
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	700
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	800
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	900
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	1000
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	1100
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	1200
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	1300
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	1400
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	1500
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	1600
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	1700
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	1800
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	1900
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	2000
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	2100
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	2200
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	2300
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	2400
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	2500
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	2600
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	2700
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	2800
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	2900
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	3000
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	3100
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	3200
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	3300
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	3400
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	3500
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	3600
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	3700
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	3800
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	3900
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	4000
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	4100
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	4200
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	4300
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	4400
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	4500
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	4600
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	4700
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	4800
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	4900
python precision_at_k.py ~/Masters/Thesis/Implementations/test_data/reference.txt ~/Masters/Thesis/Implementations/test_data/ranked.txt 	5000